// * GET DATA USERS
export const GET_DATA_USERS = "GET_DATA_USERS";
export const GET_DATA_USERS_SUCCESS = "GET_DATA_USERS_SUCCESS";
export const GET_DATA_USERS_FAILED = "GET_DATA_USERS_FAILED";

// * GET DETAIL  USER
export const GET_DETAIL_DATA_USER = "GET_DETAIL_DATA_USER";
export const GET_DETAIL_DATA_USER_SUCCESS = "GET_DETAIL_DATA_USER_SUCCESS";
export const GET_DETAIL_DATA_USER_FAILED = "GET_DETAIL_DATA_USER_FAILED";

// * POST DATA USER
export const POST_DATA_USER = "POST_DATA_USER";
export const POST_DATA_USER_SUCCESS = "POST_DATA_USER_SUCCESS";
export const POST_DATA_USER_FAILED = "POST_DATA_USER_FAILED";

// * DELETE DATA USER
export const DELETE_DATA_USER = "DELETE_DATA_USER";
export const DELETE_DATA_USER_SUCCESS = "DELETE_DATA_USER_SUCCESS";
export const DELETE_DATA_USER_FAILED = "DELETE_DATA_USER_FAILED";

// * UPDATE DATA USER
export const UPDATE_DATA_USER = "UPDATE_DATA_USER";
export const UPDATE_DATA_USER_SUCCESS = "UPDATE_DATA_USER_SUCCESS";
export const UPDATE_DATA_USER_FAILED = "UPDATE_DATA_USER_FAILED";

// * ANOTHER CONSTANT

export const USER_SET_FORM = "USER_SET_FORM";
export const CLEAR_USER_FORM = "CLEAR_USER_FORM";
export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const SET_CLOSE_MODAL = "SET_CLOSE_MODAL";
export const USER_SET_REQUEST_PARAMS = "USER_SET_REQUEST_PARAMS";
